logo: # add logo name
title: Fudushae
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: /blog
url: Fudushae.github.io

# Banner settings
video: mountains.mp4 # add banner video. Add your video file to the folder video
banner-title: # add banner title
banner-desc: # add banner description

# Author settings
author-pic: https://avatars3.githubusercontent.com/u/32151533?v=4&s=460
author-name: Fudushae
about-author: Aspiring Animator & Writer

# Social link
twitter_url:   https://twitter.com/fudushae_
facebook_url:  https://www.facebook.com/Fudushae
